Repository Mankindhufs/Mankind, pull requests merged in 2025-05, with the labels that each got.

#4 ✨ Feat : 파일 업로드 파일 마크업 및 api 초기 세팅
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Layout.tsx
  frontend/src/apis/instance.ts
  frontend/src/apis/postFile.ts
  frontend/src/assets/images/logo.png
  frontend/src/components/Spinner.tsx
  frontend/src/pages/StartPage/components/ConfirmButton.tsx
  frontend/src/pages/StartPage/components/FileInfo.tsx
  frontend/src/pages/StartPage/components/UploadBox.tsx
  frontend/src/pages/StartPage/hooks/usePostFile.ts
  frontend/src/pages/StartPage/index.tsx
  frontend/src/pages/VerifyPage/index.tsx
  frontend/src/routes/Router.tsx
Labels: ✨ Feat, 💄 Design

#9 Refactor ♻️ 기초지수 추가
  backend/requirements.txt
  backend/routes/index_api.py
  backend/services/index_service.py
Labels: ♻️ Refactor

#11 💄 Design : 헤더 위치 고정 및 로고 파일 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Layout.tsx
  frontend/src/assets/images/logo.png
  frontend/src/assets/images/logo.svg
  frontend/src/pages/Dashboard/index.tsx
  frontend/src/pages/StartPage/components/UploadBox.tsx
  frontend/src/pages/StartPage/index.tsx
  frontend/src/vite-env.d.ts
  frontend/svg.d.ts
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: 💄 Design

#13 💄 Design, 🔧 Fix : 대시보드 페이지 기초 마크업 구현 및 Layout.tsx 버그 해결
  frontend/src/Layout.tsx
  frontend/src/pages/Dashboard/components/DashboardItem.tsx
  frontend/src/pages/Dashboard/components/DueDate.tsx
  frontend/src/pages/Dashboard/components/IndexChart.tsx
  frontend/src/pages/Dashboard/components/RepaymentScenario.tsx
  frontend/src/pages/Dashboard/components/RevenueStructure.tsx
  frontend/src/pages/Dashboard/components/SearchWord.tsx
  frontend/src/pages/Dashboard/components/Sidebar.tsx
  frontend/src/pages/Dashboard/index.tsx
  frontend/src/pages/StartPage/index.tsx
Labels: 💄 Design, 🔧 Fix

#16 ✨ Feat, 💄 Design : 기초 자산 추이 그래프 구현
  .github/ISSUE_TEMPLATE/issue-template.md
  frontend/src/apis/getIndex.ts
  frontend/src/apis/instance.ts
  frontend/src/pages/Dashboard/components/DashboardItem.tsx
  frontend/src/pages/Dashboard/components/IndexChart.tsx
  frontend/src/pages/Dashboard/components/IndexChartButton.tsx
  frontend/src/pages/Dashboard/components/IndexChartItem.tsx
  frontend/src/pages/Dashboard/hooks/useGetIndex.ts
  frontend/src/typings/types.ts
Labels: ✨ Feat, 💄 Design

#17 ✨ Feat : pdf 파일 업로드 api 연결
  frontend/src/apis/postFile.ts
Labels: ✨ Feat

#22 ✨ Feat : /verify 실제 추출값 반영, 수정 기능 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Layout.tsx
  frontend/src/components/Alert.tsx
  frontend/src/pages/StartPage/hooks/usePostFile.ts
  frontend/src/pages/VerifyPage/components/EditButton.tsx
  frontend/src/pages/VerifyPage/components/EditConfirmButtons.tsx
  frontend/src/pages/VerifyPage/components/InfoRow.tsx
  frontend/src/pages/VerifyPage/components/SectionHeader.tsx
  frontend/src/pages/VerifyPage/hooks/useVerifyData.ts
  frontend/src/pages/VerifyPage/index.tsx
  frontend/src/typings/types.ts
  frontend/src/utils/format.ts
  frontend/src/utils/savedFile.ts
  frontend/src/utils/validationCheck.ts
  frontend/tailwind.config.js
Labels: ✨ Feat

#26 ✨ Feat : 대시보드 약관 전문 보기 기능 추가
  frontend/src/Layout.tsx
  frontend/src/components/Alert.tsx
  frontend/src/constants/defaultFileValue.ts
  frontend/src/pages/Dashboard/components/Sidebar.tsx
  frontend/src/pages/Dashboard/index.tsx
  frontend/src/pages/StartPage/components/UploadBox.tsx
  frontend/src/pages/VerifyPage/index.tsx
  frontend/src/utils/pdfToString.ts
Labels: ✨ Feat
